# Site settings
title: Alessandro Chiommino
description: Chiommino Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "chiommino.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alessandro Chiommino
user_description: Mi chiamo Alessandro Chiommino, sono nato nel 1986 e fin da bambino ho avuto la passione per i computer e la tecnologia.
user_title: Sistemista
email: alessandro.chiommino@gmail.com
# twitter_username: lorem_ipsum
github_username:  DrenMaisey
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
